# Generated by Django 2.1.7 on 2019-03-22 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModelForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('mail', models.EmailField(max_length=255, verbose_name='Mail')),
                ('gender', models.BooleanField(verbose_name='Gender')),
                ('department', models.CharField(max_length=255, verbose_name='Organization')),
                ('year', models.IntegerField(default=0, verbose_name='Years')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='CreateDate')),
            ],
        ),
    ]
