version: '3'

services:
  db:
    image: postgres
  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
  django:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
