version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - daphne
  daphne:
    build: .
    volumes:
      - .:/code
    command: bash -c "daphne -b 0.0.0.0 -p 8001 mysite.asgi:application"
    ports:
      - "8001:8001"
    depends_on:
      - redis
  db:
    image: postgres
  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
